name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual running from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry env use python
          poetry install --with docs

      - name: Build documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build/html

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/
