name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual running from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html/

      # Optionally, deploy to GitHub Pages or Read the Docs
      # This step would go here if you want to automate deployment
