name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual running from the GitHub UI
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry env use python
          poetry install --with docs

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build documentation
        run: |
          poetry run sphinx-build -b html docs/source docs/build/html

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
