name: Build and Publish to PyPI

on:
  release:
    types: [published]
  # Allow manual running from the GitHub UI
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag to publish (e.g., v1.0.0)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Build package
        run: |
          poetry build

      - name: Publish package to PyPI
        run: |
          poetry publish --no-interaction

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  test:
    uses: ./.github/workflows/tests.yml
